### ISSUE TITLE
Post 1000002.15-release, dot sorting is broken

### ISSUE THREAD

**Issue by Qwertdd** [casualshammy/NameplateAuras#185]
I play with no dot sorting (should only change order if a dot is dropped), and as of the most recent update, dots will randomly sort themselves with no regard for the chosen setting, and often reorder themselves mid-combat for no discernable reason.

I suspect this is due to the database update prompt that added a number of what I think were Evoker abilities, because changing NameplateAuras to an older version didn't solve my issue at all. Pictures below, sort mode is No Sorting.

Wrong from the start. This is not the order I applied these dots.
![image](https://user-images.githubusercontent.com/114839012/219256400-c15a8f97-ee75-4c3b-be96-228d54d71e27.png)

Soon into the fight, despite no dropping of any dots but Dread Touch, the order has totally reshuffled.
![image](https://user-images.githubusercontent.com/114839012/219256492-f02cb4b4-a7cd-44a8-8ea0-be1c92a22b83.png)

And once again later.
![image](https://user-images.githubusercontent.com/114839012/219256523-e390fc01-eea1-4488-b080-ea20282d42ee.png)

Thanks for any help you can provide!

**Comment by casualshammy** [comment]
Hello!
"No sorting" means addon doesn't apply any sorting to the list of auras provided by internal Blizzard API. Before `100002.9-beta` auras were scanned all at once, and order was the same. Since `100002.9-beta` NAuras uses new method for scanning auras - it scans only changed (added/removed) auras. Thus the order of auras is not determined at all if `No sorting` option is selected.
I can only recommend to use sorting.
