### ISSUE TITLE
Please Offer Option To Stack Auras

### ISSUE THREAD

**Issue by Moonfirebeam** [casualshammy/NameplateAuras#199]
This will remove a ton of screen clutter and give a much cleaner feel similar to FlyPlateBuffs. 
To clarify I mean rows and columns for stacking.
Please help this will improve the quality of my stream and also my viewers would really appreciate it as well as me :D Thank you for making this addon you're absolutely GOATed.

**Comment by 1Botnet** [comment]
Hell yeah. Please add this <3

**Comment by casualshammy** [comment]
Sorry, there are not plans to implement columns or rows. Such feature requires a ton of work due to legacy code, and could degrade performance drastically in case of many auras / many nameplates.
You can use `icon groups` feature to logically separate, for example, buffs and debuffs or auras and interrupts.

**Comment by 1Botnet** [comment]
Thanks for the reply. What about a scalable shrink past a user set number off buffs. 

So for example every buff past 6 it shrinks all buffs on that name plate by 15%. Both the number of buffs and percent shrink being user controller?
