### ISSUE TITLE
CPU Performance

### ISSUE THREAD

**Issue by void-ow** [casualshammy/NameplateAuras#201]
Hello and thank you for this addon.
I remember back in the day you had a screenshot of your CPU performance metrics for this addon so I assume this is something you'd be interested in figuring out.

I have a slightly minor complaint to impart - I've noticed that the CPU performance of this addon has started to deteriorate recently.
Here's a screenshot of test mode without any additional addons enabled:

![image](https://github.com/casualshammy/NameplateAuras/assets/38434756/eb6ffd73-89b6-494d-8b00-20c96ff590de)

This leads to 5-20ms CPU time in arena (which, I assume, depends on the amount of different spellIds I track), which is not a lot, but considering how wow handles processing by addons, this is still relevant.

Can you please take a look and see what can cause this sort of ms discrepancy?

Thanks again.

**Comment by casualshammy** [comment]
Hello.
Thank you for your interest in my addon!
I think there are two ways of considering the results of cpu profiling:

1. Relative values. For example, you install raid frames addon `A` and raid frames addon `B`. Then, you go to raid and try to kill some mythic boss, switching addons between pulls. As the result of your tests, you can conclude that addon `A` uses less cpu cycles than addon `B` **_during this particular boss fights_**. That is literally the only thing you could conclude.
2. Absolute values. Considering absolute values is useless without deep knowledge of particular addon. For example, NameplateAuras build icons cache for **_every_** spell in game when you open options GUI. This is extremely expensive operation thus it is done asynchronously in background (if I'll try to build this cache straighforward it will freeze the whole UI for 2-5 seconds). Also, test mode is much more cpu intensive than regular usage due to foolish implementation of it :) Thus absolute values in your screnshot show, erm, nothing.

But anyways, thank you for reminder about performance. I'll go to epic bg and check the relative performance. If NameplateAuras will use enormous amount of cpu cycles I'll dig in it deeper.
