### ISSUE TITLE
auras strata + nameplates (anchor: ThreatPlates)

### ISSUE THREAD

**Issue by max-striker** [casualshammy/NameplateAuras#245]
@casualshammy I hope you are having a wonderful day!

First of all, thank you for developing such an amazing addon, much appreciated

I was wondering if it is possible to resolve the following strata problem that I am facing:
(with ThreatPlates, assuming the same would happen with other cases)

1. while having no selection, is it possible to prioritize the nameplates instead (auras are overlapping nameplates ) i.e. can auras stay behind all the nameplates (to make them clickable)
![no-selection](https://github.com/user-attachments/assets/c6517365-041b-499c-8446-915ecfb107f1)

2. while selecting a target, is it possible to make non-target auras go behind the target nameplate (for visibility) while keeping other non-target auras behind the non-target nameplates just like the above example (this hinders visibility of target health, cast etc when anything comes in front of the target) 
![selected](https://github.com/user-attachments/assets/6b780150-961e-489d-be36-a983ccc7929d)

auras with higher strata than nameplates makes it hard to see targets standing next to or behind others, for an example there are 2 targets behind `jey`:
![stacked targets](https://github.com/user-attachments/assets/4bec1a81-83d8-488b-b5d8-ec0d5d791e9f)

I'm not 100% sure how well this would feel if implemented, and I know this might be a complicated case, basically asking for an option that makes auras have lower strata than the nameplate itself except the target, the following options didn't work in this case:
![target](https://github.com/user-attachments/assets/d3ca5bee-1846-4ea9-a6c6-d90276f7aaa6)

Thanks!

**Comment by casualshammy** [comment]
Hello,
I was asked for such features before, but it's quite hard to implement.
First of all, nameplate frames are placed in `WORLD` strata. This is the lowest strata, lower than `BACKGROUND`.

**Problem 1**: addons can't directly create frames in this strata, so any frame that is not placed in `WORLD` strata will always be in front of nameplates. But! There is workaround. We can "simulate" any frame strata by using frame already existing in this strata as parent. Yaay! So you can use this option:
![image](https://github.com/user-attachments/assets/4ea7ca00-13cf-4f27-9c3c-5defd89a01af)

But! The only one benefit - the target nameplate frame with auras frame will be always in front. Other aura frames will still mess with other nameplate frames because...

**Problem 2**: you cannot set frame level of frame which parent in the `WORLD` strata. So you cannot place all aura frames behind all nameplate frames. 😑

**Comment by max-striker** [comment]
Thanks for clarifying, I will try the option you mentioned, I knew there were some complications.

I did have some info about the strata levels, especially since the nameplate addons didn't give option to change strata levels in options.

Maybe I can take this issue to wow blizzard dev forums, there is a tiny chance they may implement something in future that allows manipulation of nameplates strata or some equivalent workaround.

Thanks!

**Comment by max-striker** [comment]
attaching icons directly to nameplates resolved the most important issue no.1 although it did scale up my icons but that's ok I can reduce the icon size of all added spells manually, would be nice to have option to adjust scale of non-target nameplates (this way we have control over adjusting size of non-target nameplates as well from default values - in case we use scaling by nameplate)

EDIT: was able to modify the sizes easily through the saved variables lua (find/replace)
