### ISSUE TITLE
After patch every icon size got smaller like this

### ISSUE THREAD

**Issue by hobulian** [casualshammy/NameplateAuras#70]
**Describe the bug**
After 80300.21 patch, Every icon is shrank like screenshot below. Am i have to set all aura icon size again??

**To Reproduce**
Was using 80300.16 ver but after update aura icon size changed by it's own. I am korean user using korean client and nothing special. Using Plater nameplate.

**Expected behavior**
After 80300.21 patch, Every icon is shrank like screenshot below. Is this intended??
After I applied 1.4~5x(might be 1.5 is accurate number) scale on target and icon size become similar to how it was used to be(of course only at target).

**Screenshots**
https://imgur.com/a/4QjN2nT

**Comment by casualshammy** [comment]
Hello.
Yes, this is intended behavior. It is caused by implementing a two new functions: (1) ability to scale icons on target and (2) set alpha of icons. Unfortunately, it required to make icons' scale and alpha independent from nameplates' scale and alpha (previously icons were inheriting this properties from its parent nameplates). I tried to make transition unnoticed, but players use different nameplate addons with different methods to set scale of nameplates. So, you're right, you have to set icon size once again. Sorry.
