### ISSUE TITLE
stack count not showing / scaling broken

### ISSUE THREAD

**Issue by Linbarg** [casualshammy/NameplateAuras#73]
Hey,

since the recent update my auras went kinda broken. first of all the scaling went off. every icon was like 5 pixel smaller than before. was an easy fix though, just adjusting the size, but at the same time the stack text vanished completely. no matter what size, anchor or position i try, they won't show up.

Hoping for a fix and thanks in advance!

best regards

**Comment by casualshammy** [comment]
>  first of all the scaling went off. every icon was like 5 pixel smaller than before. was an easy fix though, just adjusting the size

#70 It is caused by implementing a two new functions: (1) ability to scale icons on target and (2) set alpha of icons. Unfortunately, it required to make icons' scale and alpha independent from nameplates' scale and alpha (previously icons were inheriting this properties from its parent nameplates). I tried to make transition unnoticed, but players use different nameplate addons with different methods to set scale of nameplates. Sorry.

> the stack text vanished completely. no matter what size, anchor or position i try, they won't show up.

There is not-so-cleverly-placed option for it. Please look at the picture in this issue #68 . Make sure you have 'Show aura's stack' option enabled.

**Comment by casualshammy** [comment]
Soon a new version of addon will be available for download. Options mentioned above now placed in corresponding categories (Timer/stack text).
