### ISSUE TITLE
Icons styling

### ISSUE THREAD

**Issue by fntstk** [casualshammy/NameplateAuras#75]
Hello, I love this addon but sometimes I find it doesn't match at all with my UI style, so I would like to suggest to add the following features:

- [x] Resize icons by height and width manually
- [x] Zoom
- [x] Alpha
- [x] Borders style and offsets (like Weak Auras)

Thanks!

**Comment by casualshammy** [comment]
Hello. Thank you for suggestions!

Could you please explain what do you mean by "Zoom"?

Icons alpha is already implemented. There is category in options window.

Since [this beta](https://www.curseforge.com/wow/addons/nameplateauras/download/3071631), you can set custom texture file for borders, but Masque support (like WeakAuras) will not be implemented, as described here https://github.com/casualshammy/NameplateAuras/issues/67#issuecomment-703159671

**Comment by casualshammy** [comment]
Resize icons by height and width manually.
I will appreciate if you'll find spare time to try out the latest beta (you can install it via Twitch client or download [directly](https://www.curseforge.com/wow/addons/nameplateauras/download/3074738)). WOW client restart is required.

**Comment by fntstk** [comment]
Hello!

Sorry for the delay in my answer.

By zoom I mean the option that lets you zoom in the icon picture. If you have Weak Auras, it's the option that you can see in this screenshot. https://gyazo.com/7d82182213bccfc51bc0fbedd8bfb61a

Sure! I will test the beta tomorrow 👍 

Thanks!

**Comment by casualshammy** [comment]
I can make such option for all icons, not for particular aura. Is it OK?

**Comment by fntstk** [comment]
Sure! Appreciate it.

**Comment by casualshammy** [comment]
- [x] Zoom
I will appreciate if you'll find spare time to try out the latest beta (you can install it via Twitch client or download [directly](https://www.curseforge.com/wow/addons/nameplateauras/download/3075411)).

**Comment by fntstk** [comment]
I am already using the beta.  Everything is working! 👍 

Some notes:

Using the testing frames, while adjusting height and width manually, only the "dispellable/stealable" example auras reflect the change, but when playing everything is changed, so in the end it works.
Also I tried changing the border style using the tga file "Square_White_Border" inside \Interface\AddOns\WeakAuras\Media\Textures but it didn't work in my end, like the whole icon was the color of the border (https://gyazo.com/b2e552c14b16e1d3afa3be51943040e0), also tried moving that file inside the Media\Textures folder of NamePlaterAuras but didn't work neither, I dont know if it's maybe an incompatibility issue between the some tga files and the addon, not a problem, since the default border is already OK.

Thank you!

**Comment by casualshammy** [comment]
> Using the testing frames, while adjusting height and width manually, only the "dispellable/stealable" example auras reflect the change, but when playing everything is changed, so in the end it works.

It's intended, because (I guess) user would like to see how icons with different sizes will be placed.

>Also I tried changing the border style using the tga file "Square_White_Border" inside \Interface\AddOns\WeakAuras\Media\Textures but it didn't work in my end, like the whole icon was the color of the border (https://gyazo.com/b2e552c14b16e1d3afa3be51943040e0), also tried moving that file inside the Media\Textures folder of NamePlateAuras but didn't work neither, I dont know if it's maybe an incompatibility issue between the some tga files and the addon, not a problem, since the default border is already OK.

WeakAuras uses another method of building icons. WA's textures are intransparent, whilst NameplateAuras requires transparent textures. I've made a port for you: [Square_White_Border.zip](https://github.com/casualshammy/NameplateAuras/files/5355388/Square_White_Border.zip). Pay attention: you should not place any custom files to any addon folder, because your files may be wiped by update. Make folder like `\Interface\AddOns\custom-media` and place your files there.

**Comment by fntstk** [comment]
OK, thanks!
