### ISSUE TITLE
[feature request] icon priority system

### ISSUE THREAD

**Issue by Kheath812** [casualshammy/NameplateAuras#76]
i'd like to be able to set a priority for icons to show up at the beginning of the anchor before others. 

example: i always want sunfire to be to the left of moonfire, so i want sunfire to be priority 1 and moonfire to be priority 2 when i have sorting set to icon size and theyre both the same icon size.

**Comment by casualshammy** [comment]
Hello.
I understand the purpose of such feature, but, in your case, why you don't want to set moonfire's icon size 1px smaller (or bigger)?

**Comment by Kheath812** [comment]
> Hello.
> I understand the purpose of such feature, but, in your case, why you don't want to set moonfire's icon size 1px smaller (or bigger)?

i tried this. because of the way the ui scale is not pixel perfect anymore because of whatever blizzard changed, even a 1 px icon size different makes the icons warp in size a bit when theyre moving around which makes the difference very noticeable.

**Comment by casualshammy** [comment]
I still don't sure if I it is necessary to implement priority system. But, you can achieve desired effect if you use custom sorting feature. It became available since [this beta](https://www.curseforge.com/wow/addons/nameplateauras/download/3077673). Pay attention - WoW **restart** is required.
After installing, go to options window and make some changes:
![1](https://user-images.githubusercontent.com/4965168/95774091-aadb9d80-0cb7-11eb-9d30-1371bfc2ee6c.jpg)

Paste the following code to editor:
``` lua
function(aura1, aura2) 
    if (aura1.spellName == "Sunfire" and aura2.spellName == "Moonfire") then return true; end
    if (aura2.spellName == "Sunfire" and aura1.spellName == "Moonfire") then return false; end
    local expires1, expires2 = aura1.expires, aura2.expires;
    if (expires1 == 0) then expires1 = 30*24*60*60; end
    if (expires2 == 0) then expires2 = 30*24*60*60; end
    return expires1 < expires2;
end
```
![2](https://user-images.githubusercontent.com/4965168/95774794-03f80100-0cb9-11eb-8721-77254f780dd7.jpg)

Don't forget to replace "Sunfire" and "Moonfire" if you play non-english locale. Also, if I made a mistake in order - swap spells.

**Comment by Kheath812** [comment]
Awesome! Thanks :)

**Comment by Elbf70** [comment]
Здравствуйте, хотел бы что бы был приоритет дэбафов постоянный в такой последовательности spellID: 703(Гаррота) - 1943(Рваная рана)-121411(вихрь)-421976(капли), можно как то это сделать? спасибо))
